#
# Ludwig Docker image with full set of pre-requiste packages to support development activites:
#   text features
#   image features
#   audio features
#   visualizations
#   model serving
#   unit testing
#

#FROM intelaipg/intel-optimized-tensorflow:1.15.0-py3
FROM tensorflow/tensorflow:2.4.0-jupyter
#FROM tensorflow/tensorflow:2.1.0-py3-jupyter
#FROM tensorflow/tensorflow:latest-py3

RUN apt-get -y update && apt-get -y install git libsndfile1 cmake
#RUN pip install jupyter nbconvert

RUN pip install mkdocs mkdocs-material


# support porting to tf2 and understanding tensorflow_addons
RUN pip install nltk keras
RUN pip install dill

# pycharm plug-in to enable capturing exception in debugger with pytest
# parallel processing for pytest
RUN pip install pytest-pycharm pytest-xdist
# pytest-cov remove to see if solves hang issue in pycharm debugger

# setup to install ludwig
WORKDIR /app
COPY . /app

# install requirements for ludwig and setup for install
RUN pip uninstall tensorflow_addons \
    && pip install -r requirements_tf24.txt -r requirements_text.txt \
          -r requirements_image.txt -r requirements_audio.txt \
          -r requirements_serve.txt -r requirements_viz_matplotlib_333.txt \
          -r requirements_hyperopt.txt \
          -r requirements_test.txt \
          -r requirements_horovod.txt -r requirements_dask.txt \
          # install ludwig
          -e .

# supporting graphic packages
RUN apt-get -y install wget unzip graphviz
RUN pip install pydot pydotplus graphviz

WORKDIR /opt/project


