#
# Ludwig Docker image with full set of pre-requiste packages to support development activites:
#   text features
#   image features
#   audio features
#   visualizations
#   model serving
#   unit testing
#

#FROM intelaipg/intel-optimized-tensorflow:1.15.0-py3
FROM tensorflow/tensorflow:nightly-gpu-jupyter
#FROM tensorflow/tensorflow:2.1.0-py3-jupyter
#FROM tensorflow/tensorflow:latest-py3

RUN apt-get -y update && apt-get -y install git libsndfile1 cmake \
    libcudnn7=7.6.5.32-1+cuda10.1 \
    libnccl2=2.7.8-1+cuda10.1 \
    libnccl-dev=2.7.8-1+cuda10.1

#RUN pip install jupyter nbconvert

RUN pip install mkdocs mkdocs-material


# support porting to tf2 and understanding tensorflow_addons
RUN apt-get -y install wget unzip graphviz
RUN pip install pydot pydotplus graphviz
RUN pip install nltk
RUN pip install dill

# pycharm plug-in to enable capturing exception in debugger with pytest
# parallel processing for pytest
RUN pip install pytest-pycharm pytest-xdist pytest-cov

# setup to install ludwig
WORKDIR /app
COPY . /app

# install requirements for ludwig and setup for install of tfa_nightly
#RUN pip uninstall tensorflow  tensorflow_addons \
RUN  pip install -r requirements_tfnite.txt \
          -r requirements_image.txt -r requirements_audio.txt \
          -r requirements_serve.txt -r requirements_viz.txt \
          -r requirements_test.txt

RUN pip install -r requirements_dask.txt \
    -r requirements_ray.txt \
    -r requirements_hyperopt.txt

RUN HOROVOD_GPU_OPERATIONS=NCCL \
    HOROVOD_WITH_TENSORFLOW=1 \
    HOROVOD_WITHOUT_MPI=1 \
    HOROVOD_WITHOUT_PYTORCH=1 \
    HOROVOD_WITHOUT_MXNET=1 \
    pip install \
         --no-dependencies \
          -r requirements_hyperopt.txt

# install ludwig
RUN pip install --no-dependencies  -e .

WORKDIR /opt/project
