ARG PYTHON_VERSION=3.6
ARG LINUX_DISTRO=buster
FROM python:${PYTHON_VERSION}-${LINUX_DISTRO}

# get current with linux distro and install required tools
RUN apt-get -y update \
    && apt-get -y install git libsndfile1 cmake \
        wget unzip graphviz

# install other required tools
RUN pip install \
    jupyterlab nbconvert notebook\
    mkdocs mkdocs-material \
    pydot pydotplus graphviz \
    nltk dill matplotlib seaborn

# install pycharm related test dependencies
RUN pip install pytest-pycharm pytest-xdist pytest-cov

# additional packages for shapley value integration R&D
RUN pip install shap xgboost

# install tensorflow
ARG TENSORFLOW_VERSION
RUN echo ">>> installing tensorflow ${TENSORFLOW_VERSION}" && \
    pip install tensorflow==${TENSORFLOW_VERSION}  tensorflow_probability==0.14.1 \
        pandas scikit-learn

# set working dir for the project folder
WORKDIR /opt/project
