ARG PYTHON_VERSION=3.6
ARG LINUX_DISTRO=buster
FROM python:${PYTHON_VERSION}-${LINUX_DISTRO}

# get current with linux distro and install required tools
RUN apt-get -y update \
    && apt-get -y install git libsndfile1 cmake \
        wget unzip graphviz

# install other required tools
RUN pip install \
    jupyterlab nbconvert ipywidgets \
    mkdocs mkdocs-material \
    pydot pydotplus graphviz \
    matplotlib IProgress \
    nltk dill

# install pycharm related test dependencies
RUN pip install pytest-pycharm pytest-xdist pytest-cov


ARG TENSORFLOW_VERSION=2.5.0
ARG TORCH_VERSION=1.9.0
ARG TORCH_VISION_VERSION=0.10.0
ARG TORCH_AUDIO_VERSION=0.9.0

RUN \
    echo -e "Using TORCH Version " ${TORCH_VERSION} "\n" \
    && pip install --timeout=60 torch==${TORCH_VERSION} \
      torchvision==${TORCH_VISION_VERSION} \
      torchaudio==${TORCH_AUDIO_VERSION} \
      pytorch-lightning==1.4.4 \
      tensorflow==${TENSORFLOW_VERSION} \
      scikit-learn scikit-image pandas matplotlib seaborn


# set working dir for the project folder
WORKDIR /opt/project
