ARG PYTHON_VERSION=3.6
ARG LINUX_DISTRO=buster
FROM python:${PYTHON_VERSION}-${LINUX_DISTRO}

# get current with linux distro and install required tools
RUN apt-get -y update \
    && apt-get -y install git libsndfile1 cmake \
        wget unzip graphviz

# install other required tools
RUN pip install \
    jupyterlab nbconvert ipywidgets \
    mkdocs'<1.3' \
    mkdocs-material mike Markdown>='3.0.1' \
    pydot pydotplus graphviz \
    matplotlib IProgress \
    nltk dill

# install pycharm related test dependencies
RUN pip install pytest-pycharm pytest-xdist pytest-cov


# setup for ludwig install
WORKDIR /app
COPY . /app

ENV HOROVOD_WITHOUT_TENSORFLOW=1
ENV HOROVOD_WITHOUT_MPI=1
ENV HOROVOD_WITH_PYTORCH=1
ENV HOROVOD_WITHOUT_MXNET=1
ENV MAKEFLAGS="-j 12"
# install ludwig and pre-reqs
#RUN  pip install -e .[hyperopt,viz]
RUN pip install ludwig==0.5.2

# install graph vizualization
RUN pip install -U git+https://github.com/szagoruyko/pytorchviz.git@master

# install torchtest packages
RUN pip install --upgrade torchtest

# to debug memory leak
RUN pip install pympler

# code quality checker
RUN pip install pre-commit


# set working dir for the project folder
WORKDIR /opt/project
